server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://<RDS-엔드포인트>:3306/reactdb
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    aws:
      credentials:
        access-key: <IAM_ACCESS_KEY>
        secret-key: <IAM_SECRET_KEY>
      s3:
        bucket: <버킷이름>
        region: ap-northeast-2

jwt:
  secret: mySecretKey0000dfadfasdfdsafdasffsfafsafasdfddfsdafs
  expiration: 1800000
